spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/portfolio
    username: portfolio_user
    password: portfolio_pass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    host: smtp.ionos.fr
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

contact:
  mail:
    to: ${MAIL_TO}

server:
  port: 8080

frontend:
  url: ${FRONTEND_URL:http://localhost:4200}